root: true
env:
    browser: true
    es2021: true
    'jest/globals': true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - prettier
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 13
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
    - prettier
    - testing-library
    - jest
settings:
    react:
        version: 'detect'
rules:
    indent:
        - 'error'
        - 4
        - VariableDeclarator: 'first'
          FunctionDeclaration:
              parameters: 'first'
          CallExpression:
              arguments: 'first'
          ArrayExpression: 'first'
          ObjectExpression: 'first'
          ImportDeclaration: 'first'
    no-multiple-empty-lines:
        - 'error'
        - max: 2
          maxEOF: 1
          maxBOF: 0
    quotes:
        - 'warn'
        - 'single'
    prettier/prettier: error
