name: Build
on: [pull_request]
jobs:
    ESLint-Check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
            - name: Node version
              run: node --version
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
