name: Lint & Style
on: [push]
jobs:
    ESLint-Check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
            #   with:
            #       node-version: '16'
            - name: Node version
              run: node --version
            - name: Install Modules
              run: npm install eslint prettier
            - name: Run ESLint Check
              run: npm run lint
            - name: Run Prettier Check
              run: npx prettier --check .
